version = 1

[[migrations]]
id = 8447594227695919011
name = "0000_spire_tables.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 1077069251563642058
name = "0001_fitness_tables.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 7815188195082200382
name = "0002_analytics_tables.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 6268874536935372237
name = "0003_analytics_visitor_aliases.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 1462502880782735015
name = "0004_analytics_server_sessions.sql"
snapshot_name = "0004_snapshot.toml"
