version = 1

[[migrations]]
id = 8447594227695919011
name = "0000_spire_tables.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 1077069251563642058
name = "0001_fitness_tables.sql"
snapshot_name = "0001_snapshot.toml"
