version = 1

[schema]

[[schema.tables]]
id = 0
name = "exercises"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_exercises_by_name"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 1
name = "fitness_meta"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "k"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "v"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_fitness_meta_by_k"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "sets"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "workout_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "exercise_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "raw_exercise_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "ordinal"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "exercise_note"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 6 }
name = "superset_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 7 }
name = "weight_milli"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 8 }
name = "weight_unit"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 9 }
name = "reps"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 10 }
name = "effort_hundredths"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 11 }
name = "distance_milli"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 12 }
name = "set_time_seconds"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 13 }
name = "set_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 14 }
name = "incomplete"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_sets_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_sets_by_workout_id_and_ordinal"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 2, index = 4 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_sets_by_workout_id"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "exercise_tags"
primary_key = { columns = [{ table = 3, index = 0 }, { table = 3, index = 1 }, { table = 3, index = 2 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "exercise_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "kind"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "value"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_exercise_tags_by_exercise_name_and_kind_and_value"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }, { column = { table = 3, index = 1 }, op = "Eq", scope = "Local" }, { column = { table = 3, index = 2 }, op = "Eq", scope = "Local" }]
unique = true
primary_key = true

[[schema.tables]]
id = 4
name = "workouts"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "title"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "raw_title"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 3 }
name = "started_at_utc"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 4 }
name = "started_at_local"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 5 }
name = "eastern_offset_minutes"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 6 }
name = "duration_seconds"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 7 }
name = "duration_suspicious"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 4, index = 8 }
name = "notes"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 9 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 10 }
name = "source"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 11 }
name = "imported_at"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_workouts_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_workouts_by_started_at_utc"
on = 4
columns = [{ column = { table = 4, index = 3 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 5
name = "spire_run_raws"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "raw"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_spire_run_raws_by_id"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 6
name = "spire_meta"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "k"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "v"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_spire_meta_by_k"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 7
name = "spire_runs"
primary_key = { columns = [{ table = 7, index = 0 }], index = { table = 7, index = 0 } }

[[schema.tables.columns]]
id = { table = 7, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 1 }
name = "date"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 2 }
name = "start_time"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 3 }
name = "character"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 4 }
name = "win"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 7, index = 5 }
name = "abandoned"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 7, index = 6 }
name = "ascension"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 7 }
name = "acts"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 8 }
name = "floors"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 9 }
name = "killed_by"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 10 }
name = "kill_kind"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 11 }
name = "run_time"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 12 }
name = "seed"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 13 }
name = "game_mode"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 14 }
name = "build_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 15 }
name = "added_at"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.indices]]
id = { table = 7, index = 0 }
name = "index_spire_runs_by_id"
on = 7
columns = [{ column = { table = 7, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 7, index = 1 }
name = "index_spire_runs_by_start_time"
on = 7
columns = [{ column = { table = 7, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 8
name = "analytics_identities"
primary_key = { columns = [{ table = 8, index = 0 }], index = { table = 8, index = 0 } }

[[schema.tables.columns]]
id = { table = 8, index = 0 }
name = "visitor_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 8, index = 1 }
name = "display_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 8, index = 2 }
name = "note"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 8, index = 3 }
name = "first_submitted_at"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 8, index = 4 }
name = "updated_at"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.indices]]
id = { table = 8, index = 0 }
name = "index_analytics_identities_by_visitor_id"
on = 8
columns = [{ column = { table = 8, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 9
name = "analytics_events"
primary_key = { columns = [{ table = 9, index = 0 }], index = { table = 9, index = 0 } }

[[schema.tables.columns]]
id = { table = 9, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 1 }
name = "visitor_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 2 }
name = "session_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 3 }
name = "occurred_at"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 9, index = 4 }
name = "kind"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 5 }
name = "page_path"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 6 }
name = "referrer_kind"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 7 }
name = "referrer_host"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 8 }
name = "referrer_path"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 9 }
name = "country_code"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 10 }
name = "timezone"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 11 }
name = "language"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 12 }
name = "device_kind"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 13 }
name = "browser"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 14 }
name = "operating_system"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 15 }
name = "viewport_kind"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 9, index = 16 }
name = "navigation_kind"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 17 }
name = "local_hour"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 18 }
name = "local_weekday"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 19 }
name = "engagement_seconds"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 20 }
name = "scroll_percent"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 21 }
name = "lcp_milliseconds"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 22 }
name = "cls_thousandths"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 23 }
name = "navigation_milliseconds"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 24 }
name = "target_host"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 25 }
name = "utm_source"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 26 }
name = "utm_medium"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 9, index = 27 }
name = "utm_campaign"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 9, index = 0 }
name = "index_analytics_events_by_id"
on = 9
columns = [{ column = { table = 9, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 9, index = 1 }
name = "index_analytics_events_by_kind_and_occurred_at"
on = 9
columns = [{ column = { table = 9, index = 4 }, op = "Eq", scope = "Partition" }, { column = { table = 9, index = 3 }, op = "Eq", scope = "Local" }]

[[schema.tables.indices]]
id = { table = 9, index = 2 }
name = "index_analytics_events_by_occurred_at"
on = 9
columns = [{ column = { table = 9, index = 3 }, op = "Eq", scope = "Partition" }]
